services:

  waha:
    image: devlikeapro/waha:latest
    container_name: wppbotwaha
    restart: always
    ports:
      - "3000:3000"
    environment:
      - WHATSAPP_ENGINE=NOWEB
      - WAHA_PRINT_QR=True
    env_file:
      - .env
    volumes:
      - waha_sessions:/app/.waha   # persistência da sessão

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: wppbotapi
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - WAHA_API_URL=http://waha:3000
    volumes:
      - ./rag:/app/rag
      - chroma_data:/app/chroma_data
      - ./entrypoint.sh:/app/entrypoint.sh
    depends_on:
      - waha
    command: ["/bin/sh","/app/entrypoint.sh"]

volumes:
  waha_sessions:
  chroma_data:
  